workshop protected arguments warning
tidymodels/parsnip pull request #1216
Opened 2024-10-24 13:42 UTC by simonpcouch

I came across this warning while spring cleaning bonsai and felt that it was reasonable that we tested for it but not that we screenshotted it. This PR adds a warning subclass and corrects pluralization in the message.

2024-10-24 13:45 UTC, simonpcouch commented on tests/testthat/test-arguments.R
Note that this is a totally new test file. This warning is tested in a couple engine-specific files already—I just test for the subclass now.

2024-10-24 13:45 UTC, simonpcouch commented on tests/testthat/_snaps/mlp.md
> ----
Each of these removed snapshots both tested duplicates of the print method and this warning message.

2024-10-24 13:46 UTC, simonpcouch commented
I imagine this will cause snap changes in many places in extratests and parsnip extensions. Those should be able to just test the warning class now.😜

2024-10-24 16:55 UTC, hfrick requested changes
Generally totally on board with this but hitting "request changes" to make that part obvious. Happy for you to merge after that's fixed 👍

2024-10-24 16:55 UTC, hfrick commented on R/arguments.R
> -    args <- args[!(names(args) %in% common_args)]
You do not want to remove this line :)

2024-10-25 19:16 UTC, simonpcouch commented on R/arguments.R
> -    args <- args[!(names(args) %in% common_args)]
Ah, thank you!

2024-10-25 19:30 UTC, merged