Set event level for xgboost
tidymodels/parsnip pull request #436
Opened 2021-02-26 18:33 UTC by hfrick

This closes #420 and allows users to set which level is used as the event for binary classification.

2021-03-02 15:35 UTC, hfrick commented
The reprex from the issue now looks like this: the default setting (= the first factor level is the event) is giving the same result as you would expect from xgboost and setting `event_level = "second"` gives you the previous behaviour.

``` r
library(tidyverse)
library(tidymodels)
library(mlbench)
library(xgboost)
#> 
#> Attaching package: 'xgboost'
#> The following object is masked from 'package:dplyr':
#> 
#>     slice

data("PimaIndiansDiabetes")

set.seed(24)
df <- PimaIndiansDiabetes %>%
  mutate(diabetes = fct_relevel(diabetes, 'pos'))


# xgboost
x <- as.matrix(df[,-ncol(df)])
y <- if_else(as.numeric(df$diabetes) == 2, 0, 1)

xgbmat <- xgb.DMatrix(data = x, label = y)

set.seed(24)
xgboost::xgb.train(params = list(eta = 0.3, max_depth = 3, gamma = 0, 
                                 colsample_bytree = 1, min_child_weight = 1, subsample = 1), 
                   data = xgbmat, nrounds = 10, watchlist = list('train' = xgbmat), verbose = 1, 
                   objective = "binary:logistic", eval_metric = "aucpr", 
                   nthread = 1)
#> [1]  train-aucpr:0.727241 
#> [2]  train-aucpr:0.745081 
#> [3]  train-aucpr:0.764679 
#> [4]  train-aucpr:0.779323 
#> [5]  train-aucpr:0.798561 
#> [6]  train-aucpr:0.812330 
#> [7]  train-aucpr:0.822405 
#> [8]  train-aucpr:0.824102 
#> [9]  train-aucpr:0.828753 
#> [10] train-aucpr:0.839825
#> ##### xgb.Booster
#> raw: 14.7 Kb 
#> call:
#>   xgboost::xgb.train(params = list(eta = 0.3, max_depth = 3, gamma = 0, 
#>     colsample_bytree = 1, min_child_weight = 1, subsample = 1), 
#>     data = xgbmat, nrounds = 10, watchlist = list(train = xgbmat), 
#>     verbose = 1, objective = "binary:logistic", eval_metric = "aucpr", 
#>     nthread = 1)
#> params (as set within xgb.train):
#>   eta = "0.3", max_depth = "3", gamma = "0", colsample_bytree = "1", min_child_weight = "1", subsample = "1", objective = "binary:logistic", eval_metric = "aucpr", nthread = "1", validate_parameters = "TRUE"
#> xgb.attributes:
#>   niter
#> callbacks:
#>   cb.print.evaluation(period = print_every_n)
#>   cb.evaluation.log()
#> # of features: 8 
#> niter: 10
#> nfeatures : 8 
#> evaluation_log:
#>     iter train_aucpr
#>        1    0.727241
#>        2    0.745081
#> ---                 
#>        9    0.828753
#>       10    0.839825


# parsnip default: first factor level is the event
xgb_model_1 <- boost_tree(trees = 10, tree_depth = 3) %>%
  set_engine('xgboost', 
             eval_metric = 'aucpr',
             verbose = 1) %>%
  set_mode('classification')

xgb_model_1 %>%
  fit(diabetes ~ . , df)
#> [1]  training-aucpr:0.727241 
#> [2]  training-aucpr:0.745081 
#> [3]  training-aucpr:0.764679 
#> [4]  training-aucpr:0.779323 
#> [5]  training-aucpr:0.798561 
#> [6]  training-aucpr:0.812330 
#> [7]  training-aucpr:0.822405 
#> [8]  training-aucpr:0.824102 
#> [9]  training-aucpr:0.828753 
#> [10] training-aucpr:0.839825
#> parsnip model object
#> 
#> Fit time:  18ms 
#> ##### xgb.Booster
#> raw: 14.7 Kb 
#> call:
#>   xgboost::xgb.train(params = list(eta = 0.3, max_depth = 3, gamma = 0, 
#>     colsample_bytree = 1, min_child_weight = 1, subsample = 1, 
#>     objective = "binary:logistic"), data = x$data, nrounds = 10, 
#>     watchlist = x$watchlist, verbose = 1, eval_metric = "aucpr", 
#>     nthread = 1)
#> params (as set within xgb.train):
#>   eta = "0.3", max_depth = "3", gamma = "0", colsample_bytree = "1", min_child_weight = "1", subsample = "1", objective = "binary:logistic", eval_metric = "aucpr", nthread = "1", validate_parameters = "TRUE"
#> xgb.attributes:
#>   niter
#> callbacks:
#>   cb.print.evaluation(period = print_every_n)
#>   cb.evaluation.log()
#> # of features: 8 
#> niter: 10
#> nfeatures : 8 
#> evaluation_log:
#>     iter training_aucpr
#>        1       0.727241
#>        2       0.745081
#> ---                    
#>        9       0.828753
#>       10       0.839825

# parsnip with event_level = "second"
xgb_model_2 <- boost_tree(trees = 10, tree_depth = 3) %>%
  set_engine('xgboost', 
             eval_metric = 'aucpr',
             event_level = "second",
             verbose = 1) %>%
  set_mode('classification')

xgb_model_2 %>%
  fit(diabetes ~ . , df)
#> [1]  training-aucpr:0.886176 
#> [2]  training-aucpr:0.914292 
#> [3]  training-aucpr:0.928699 
#> [4]  training-aucpr:0.929974 
#> [5]  training-aucpr:0.934629 
#> [6]  training-aucpr:0.939465 
#> [7]  training-aucpr:0.942369 
#> [8]  training-aucpr:0.944927 
#> [9]  training-aucpr:0.948185 
#> [10] training-aucpr:0.949217
#> parsnip model object
#> 
#> Fit time:  15ms 
#> ##### xgb.Booster
#> raw: 14.7 Kb 
#> call:
#>   xgboost::xgb.train(params = list(eta = 0.3, max_depth = 3, gamma = 0, 
#>     colsample_bytree = 1, min_child_weight = 1, subsample = 1, 
#>     objective = "binary:logistic"), data = x$data, nrounds = 10, 
#>     watchlist = x$watchlist, verbose = 1, eval_metric = "aucpr", 
#>     nthread = 1)
#> params (as set within xgb.train):
#>   eta = "0.3", max_depth = "3", gamma = "0", colsample_bytree = "1", min_child_weight = "1", subsample = "1", objective = "binary:logistic", eval_metric = "aucpr", nthread = "1", validate_parameters = "TRUE"
#> xgb.attributes:
#>   niter
#> callbacks:
#>   cb.print.evaluation(period = print_every_n)
#>   cb.evaluation.log()
#> # of features: 8 
#> niter: 10
#> nfeatures : 8 
#> evaluation_log:
#>     iter training_aucpr
#>        1       0.886176
#>        2       0.914292
#> ---                    
#>        9       0.948185
#>       10       0.949217
```

<sup>Created on 2021-03-02 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

2021-03-02 16:13 UTC, topepo requested changes
Looks great overall.

2021-03-02 16:13 UTC, topepo commented on man/rmd/boost-tree.Rmd
> +Finally, note that `xgboost` models require that non-numeric predictors (e.g., factors) must be converted to dummy variables or some other numeric representation. By default, when using `fit()` with
```suggestion
Note that `xgboost` models require that non-numeric predictors (e.g., factors) must be converted to dummy variables or some other numeric representation. By default, when using `fit()` with `xgboost`, a one-hot encoding is used to convert factor predictors to indicator variables. 

Finally, in the classification mode, non-numeric outcomes (i.e., factors) are converted to numeric. For binary classification, the `event_level` argument of `set_engine()` can be set to either `"first"` or `"second"` to specify which level should be used as the event. This can be helpful when a watchlist is used to monitor performance from with the xgboost training process. 
```

2021-03-08 00:44 UTC, topepo approved these changes

2021-03-31 17:00 UTC, merged