add gen_additive_mod
tidymodels/parsnip pull request #512
Opened 2021-06-10 18:03 UTC by mdancho84

Hey @topepo et al, 
Here is the work-in-progress version of the `gen_additive_mod()` function. I'm OK with changing anything, I'd just like to see GAM's get into `parsnip`.

2021-06-11 16:02 UTC, topepo commented on R/gen_additive_mod_data.R
> +            which(max(x) == x)[1]) - 1 %>% #modify in the future for something more elegant when gets the formula ok
Can you talk about this for a min? What is going on there?

2021-06-11 16:04 UTC, topepo commented
Thanks for send this in. 

Do we want to have `gam` as an engine? They frequently update the package to the most recent version of R and make breaking changes (without much developer sympathy/consideration). At the minimum, I'd like to make the default engine `mgcv`. 

We're almost done with a new documentation system for `parsnip` and I've adjusted the doc file (incompletely) to prepare for this. (I'll do a `modeltime` PR to show how it is done; it is opt-in).

2021-06-13 19:20 UTC, mdancho84 commented on R/gen_additive_mod_data.R
> +            which(max(x) == x)[1]) - 1 %>% #modify in the future for something more elegant when gets the formula ok
Hey, Alberto wrote this part. I need to ask.

2021-06-13 19:22 UTC, mdancho84 commented
> Thanks for send this in.
> 
> Do we want to have `gam` as an engine? They frequently update the package to the most recent version of R and make breaking changes (without much developer sympathy/consideration). At the minimum, I'd like to make the default engine `mgcv`.
> 
> We're almost done with a new documentation system for `parsnip` and I've adjusted the doc file (incompletely) to prepare for this. (I'll do a `modeltime` PR to show how it is done; it is opt-in).

Hey, I'll leave this one up to you. `mgcv::gam()` is the function that is being used, so maybe `mgcv` is fine.

2021-06-13 20:01 UTC, AlbertoAlmuinha commented on R/gen_additive_mod_data.R
> +            which(max(x) == x)[1]) - 1 %>% #modify in the future for something more elegant when gets the formula ok
Hi @topepo ,

The intent of that part of the code is to obtain the class in a multi-class classification problem. If I remember correctly, that part of the code is not tested precisely because we didn't know how to implement the multiclass classification models, you can see the issue we opened in the following link (the problem was specifically with the type of "formula" used with these models):

https://github.com/business-science/gammodels/issues/11

2021-06-15 15:29 UTC, hfrick requested changes

2021-06-15 15:29 UTC, hfrick commented on R/gen_additive_mod.R
> +#' __gam__
The documentation style doesn't match the current one, neither does it match the new work-in-progress one. Do we want to use either of these @topepo ?

2021-06-15 15:29 UTC, hfrick commented on R/gen_additive_mod_data.R
> +set_new_model("gen_additive_mod")
don't we also need a `set_model_mode()`?

2021-06-15 15:29 UTC, hfrick commented on R/gen_additive_mod_data.R
> +    },
Could this all go into its own function instead of being defined inline? it's a bit long for that.

2021-06-15 15:29 UTC, hfrick commented on R/gen_additive_mod_data.R
> +    },
same comment as on the corresponding part for the regression mode

2021-06-15 15:29 UTC, hfrick commented on tests/testthat/test_gen_additive_model.R
> +reg_mod <- gen_additive_mod(select_features = TRUE) %>% set_engine("mgcv") %>% set_mode("regression")
could we move this into the `test_that()` so that it is self-contained?

2021-06-15 15:29 UTC, hfrick commented on tests/testthat/test_gen_additive_model.R
> +cls_mod <- gen_additive_mod(adjust_deg_free = 1.5) %>% set_engine("mgcv") %>% set_mode("classification")
this one could also easily go into the call to `test_that()` to make that self-contained

2021-06-16 01:57 UTC, topepo approved these changes

2021-06-16 15:42 UTC, hfrick approved these changes

2021-06-16 15:56 UTC, merged