check for non-numeric cols when converting to matrix
tidymodels/parsnip pull request #594
Opened 2021-11-08 16:21 UTC by topepo

`maybe_matrix()` not checks and gives an informative error when non-numeric columns are present.

2021-11-09 14:05 UTC, DavisVaughan requested changes

2021-11-09 14:05 UTC, DavisVaughan commented on R/convert_data.R
> +    cat_cols <- vapply(x, function(x) !is.numeric(x), logical(1))
They aren't necessarily categorical, so I'd just call these `non_num_cols` rather than `cat_cols`

2021-11-09 14:05 UTC, DavisVaughan commented on R/convert_data.R
> +      cat_cols <- paste0("'", cat_cols, "'", collapse = ", ")
Since we use glue 

```suggestion
      cat_cols <- glue::glue_collapse(glue::single_quote(cat_cols), sep = ", ")
```

2021-11-09 14:05 UTC, DavisVaughan commented on R/convert_data.R
> +                        "converted to numeric matrix: {cat_cols}")
```suggestion
                        "converted to numeric matrix: {cat_cols}.")
```

2021-11-09 14:05 UTC, DavisVaughan commented on R/convert_data.R
> +      msg <- glue::glue("Some columns are non-numeric. The data cannot be",
```suggestion
      msg <- glue::glue("Some columns are non-numeric. The data cannot be ",
```

2021-11-09 14:05 UTC, DavisVaughan commented on tests/testthat/test_convert_data.R
> +  expect_error(
We should really update parsnip to testthat 3e so we can do `expect_snapshot(error = TRUE, {code})`

2021-11-10 15:32 UTC, topepo commented on R/convert_data.R
> +    cat_cols <- vapply(x, function(x) !is.numeric(x), logical(1))
There could be _a lot_ of columns and I assume that `vapply()` is a smidgeon fast.

2021-11-11 21:42 UTC, topepo commented
Merging despite failures on windows. These are due to issue compiling the new xgboost version and, hopefully, binaries will be available soon.

2021-11-11 21:42 UTC, merged