Deprecate `varying()` and `varying_args()`
tidymodels/parsnip pull request #636
Opened 2022-01-19 23:12 UTC by EmilHvitfeldt

This PR aims to close https://github.com/tidymodels/parsnip/issues/559.

The changes are

- reexport tune from hardhat. This change doesn't give conflicts with dev version of tune, which also reexports from hardhat.

``` r
library(parsnip)
library(tune)
```

<sup>Created on 2022-01-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

- lifecycle changes to start deprecation process
- remove usage of `varying()` and `varying_args()` internally in package code and tests
- update "getting started" vignette

2022-01-20 17:41 UTC, hfrick commented
should we make explicit that `tune()` is in hardhat and `tune_args()` in generics (and neither is in parsnip)?

2022-01-21 04:56 UTC, EmilHvitfeldt commented
If you are referring to the "Getting Started" page. Then I would vote to not mention it. {hardhat} at least is a very developer focused package that most users will never touch, and bringing it up in the introduction might send the wrong message

2022-01-21 09:49 UTC, hfrick commented
Totally agree about not mentioning it in the Getting Started page for the reasons you mentioned. Sorry I wasn't clear - I meant in the calls to `lifecycle::deprecate_soft()` like in the [lifecycle vignette](https://lifecycle.r-lib.org/articles/communicate.html#deprecate-a-function-1) and perhaps the NEWS. I'll leave a code suggestion for illustration.

2022-01-21 09:50 UTC, hfrick commented on R/varying.R
> +  lifecycle::deprecate_soft("0.1.8", "varying()", "tune()")
```suggestion
  lifecycle::deprecate_soft("0.1.8", "varying()", "hardhat::tune()")
```

2022-01-31 15:01 UTC, topepo requested changes
Wherever you can link to tune, that would be good.

2022-01-31 19:44 UTC, merged