Update internal functions to reflect deprecated keras functions
tidymodels/parsnip pull request #639
Opened 2022-01-26 22:34 UTC by EmilHvitfeldt

This PR aims to close https://github.com/tidymodels/parsnip/issues/613 and close https://github.com/tidymodels/parsnip/issues/596.

With the changes to tensorflow, internal functions have been updated to reflect deprecated functions.

2022-02-02 00:49 UTC, topepo requested changes
Also, please make an entry in the news file about this.

2022-02-02 00:49 UTC, topepo commented on R/mlp.R
> +keras_predict_classes <- function(object, x)  {
Is the reason that we are returning integers related to availability of the factor levels?

2022-02-02 00:49 UTC, topepo commented on tests/testthat/test_linear_reg_keras.R
> +  if (tensorflow::tf_version() >= package_version("2.0")) {
Should we write a wrapper for this (`set_tf_seed()`) and export it?

2022-02-02 01:57 UTC, EmilHvitfeldt commented on R/mlp.R
> +keras_predict_classes <- function(object, x)  {
I assume that this was initially done because that was what {keras} did. We are converting those integers back to factors, in the `post` part of prediction
https://github.com/tidymodels/parsnip/blob/0c7f44080b57c7b79e15e35c932eb1a1d2745508/R/mlp_data.R#L149-L151

2022-02-02 02:10 UTC, EmilHvitfeldt commented on tests/testthat/test_linear_reg_keras.R
> +  if (tensorflow::tf_version() >= package_version("2.0")) {
Yes, let us do that

2022-02-03 13:16 UTC, topepo commented on R/mlp.R
> +keras_predict_classes <- function(object, x)  {
Can we do that in this function? It would be more clean.

2022-02-03 17:52 UTC, EmilHvitfeldt commented on tests/testthat/test_mlp_keras.R
> +  xy_pred <- predict(xy_fit$fit, x = as.matrix(hpc[1:8, num_pred])) %>% keras::k_argmax() %>% as.integer()
I'm gonna swap between the prediction styles conditionally on the tensorflow version such that the "old tensorflow" GHA can check those tests. Otherwise we didn't need that GHA

2022-02-04 01:16 UTC, EmilHvitfeldt commented on R/mlp.R
> +keras_predict_classes <- function(object, x)  {
Done!

2022-02-04 01:17 UTC, EmilHvitfeldt commented on tests/testthat/test_linear_reg_keras.R
> +  if (tensorflow::tf_version() >= package_version("2.0")) {
Done!

2022-02-04 01:17 UTC, EmilHvitfeldt commented on tests/testthat/test_mlp_keras.R
> +  xy_pred <- predict(xy_fit$fit, x = as.matrix(hpc[1:8, num_pred])) %>% keras::k_argmax() %>% as.integer()
Done!

2022-02-04 01:17 UTC, EmilHvitfeldt commented on DESCRIPTION
> +Remotes:
Removed!

2022-02-08 17:50 UTC, t-kalinowski commented on R/mlp.R
> +      index <- preds %>% keras::k_argmax() %>% as.integer()
If performance becomes an issue, you may want to avoid using k_argmax() here because it introduces another somewhat expensive full conversation from R -> python -> R

2022-02-08 17:50 UTC, t-kalinowski commented on R/mlp.R
> +  if (utils::packageVersion("keras") >= package_version("2.6")) {
You probably want to test the tensorflow version here `tf_version()`, not the R package version

2022-02-08 17:55 UTC, EmilHvitfeldt commented on R/mlp.R
> +      index <- preds %>% keras::k_argmax() %>% as.integer()
Okay, we could write our own `k_argmax()` function if we run into complaints

2022-02-08 18:01 UTC, EmilHvitfeldt commented on R/mlp.R
> +  if (utils::packageVersion("keras") >= package_version("2.6")) {
Are you saying to test the tensorflow version instead of the keras version or in addition?

2022-02-08 18:09 UTC, t-kalinowski commented on R/mlp.R
> +  if (utils::packageVersion("keras") >= package_version("2.6")) {
Can you use `predict` directly in all versions?

2022-02-08 18:26 UTC, EmilHvitfeldt commented on R/mlp.R
> +  if (utils::packageVersion("keras") >= package_version("2.6")) {
doesn't work for all versions :(

I get the following error if I try to switch to `predict()` only for `utils::packageVersion("keras") == "2.4.0"`

```
<Rcpp::exception/C++Error/error/condition>
Error in `py_call_impl(callable, dots$args, dots$keywords)`: AttributeError: 'Sequential' object has no attribute 'shape'
```

2022-02-08 18:42 UTC, EmilHvitfeldt commented
This PR tries to handle a couple of different problems.

The first problem is the error emitted by Keras as mentioned in #613 and #596, where `predict_classes` and `predict_proba` were changed. There is now a conditional (version(keras) >= 2.6) on the package version of `keras` to switch between using `predict()` and `predict_proba()`

Secondly the use of `keras::k_argmax()` is conditioned to be used when the tensorflow version is v2.

Lastly, `set_tf_seed()` has been added, exported and used in tests. This function sets seed in R and tensorflow at the same time, conditionally switching between `tensorflow::tf$random$set_seed` and `tensorflow::tf$random$set_random_seed` for v1 and v2 respectively.

I have tested these changes locally using all combinations that could be installed together of

- Keras: 2.7.0, 2.6.1, 2.6.0, 2.4.0
- Tensorflow: 2.7.1, 2.6.3, 1.15.0

2022-02-08 18:55 UTC, t-kalinowski commented on R/mlp.R
> +  if (utils::packageVersion("keras") >= package_version("2.6")) {
Do you maybe have a reprex you can share?

2022-02-08 19:30 UTC, topepo commented on R/mlp.R
> +      index <- preds %>% keras::k_argmax() %>% as.integer()
Would something like `apply(x, 1, which.max)` work?

2022-02-08 19:40 UTC, EmilHvitfeldt commented on R/mlp.R
> +  if (utils::packageVersion("keras") >= package_version("2.6")) {
My mistake. I updated in https://github.com/tidymodels/parsnip/pull/639/commits/12ce5b85d4a10e3bdda810a1d96fdcb5eb0d11f0

2022-02-09 00:29 UTC, t-kalinowski commented on R/mlp.R
> +      index <- preds %>% keras::k_argmax() %>% as.integer()
also, for matrices (`length(dim(x)) == 2`) you can use `max.col()`

2022-02-09 02:18 UTC, merged