prompt on unavailable extension packages
tidymodels/parsnip pull request #732
Opened 2022-05-22 20:16 UTC by simonpcouch

Closes #731.

I've had a few moments of confusion as I've familiarized with parsnip where I unknowingly specify a model specification/engine/mode combination that requires an extension package, and only come across failures later on in a modeling pipeline. This seems to be the source of confusion in #544 as well.

This PR refines print methods to nudge users to load an extension package if it's needed.

``` r
# warns informatively when it ought to:
library(parsnip)

C5_rules()
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0 
#> 
#> A parsnip implementation for `C5_rules` classification model specifications using the `C5.0` engine is not loaded.
#> The parsnip extension package {rules} implements support for this specification/mode/engine combination. 
#> Please install (if needed) and load to continue.

C5_rules(engine = "C5.0") %>% translate()
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0 
#> 
#> A parsnip implementation for `C5_rules` classification model specifications using the `C5.0` engine is not loaded.
#> The parsnip extension package {rules} implements support for this specification/mode/engine combination. 
#> Please install (if needed) and load to continue.

# doesn't prompt and prints out the call as before if the implementing extension is loaded:
library(rules)

C5_rules()
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0

C5_rules(engine = "C5.0") %>% translate()
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0 
#> 
#> Model fit template:
#> rules::c5_fit(x = missing_arg(), y = missing_arg(), weights = missing_arg())

# otherwise behaves the same as before:
linear_reg() %>% translate()
#> Linear Regression Model Specification (regression)
#> 
#> Computational engine: lm 
#> 
#> Model fit template:
#> stats::lm(formula = missing_arg(), data = missing_arg(), weights = missing_arg())

linear_reg()
#> Linear Regression Model Specification (regression)
#> 
#> Computational engine: lm
```

<sup>Created on 2022-05-22 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This prompt could also live in an actual `rlang::inform`, or even an `rlang::warn` if called inside of `translate`—open to adjusting if that's preferred.

2022-05-22 22:23 UTC, juliasilge commented
I think this would make the most sense in an `rlang::inform()` vs. printing (and we have a lot of tools for handling the rlang messages).

2022-05-22 22:38 UTC, simonpcouch commented
Ah, thank you @juliasilge! I agree that `rlang::inform` likely makes more sense.

Just pushed those changes—they're a bit more invasive now but do result in a better interface.

2022-05-22 23:09 UTC, simonpcouch commented
Wrapping up for the night, though this isn't quite there.🌝🌚

2022-05-23 20:46 UTC, simonpcouch reviewed
A quick self-review to give some context for changes. :)

2022-05-23 20:46 UTC, simonpcouch commented on R/misc.R
> -  if (
Gets rid of these conditionals as the code pointed to in the `is.null(object$method$fit$func["pkg"])` condition is what resulted in the `call2` errors noted in the issue reprex. Couldn't find coverage for those lines before this PR, so I think that code was otherwise unused.

2022-05-23 20:46 UTC, simonpcouch commented on R/bag_mars.R
> +  if (!is.null(x$method$fit$args) && has_loaded_implementation(class(x)[1], x$engine, x$mode)) {
Most of the files changed are of this form—the additional condition guards us from printing `"Model fit template"` and then reaching the condition that would result in the `call2` error from the issue reprex.

2022-05-24 21:14 UTC, juliasilge commented on R/misc.R
> +new_model_spec <- function(cls, args, eng_args, mode, method, engine, new = TRUE) {
I don't know if this is just a naming issue, but `new_model_spec(new = TRUE)` or even worse `FALSE` 😱 seems weird to me, and I am almost sure I will be super confused if I come back to this later. Do you have any ideas on this?

2022-05-24 21:39 UTC, juliasilge reviewed
It will be a huge help to give more useful info in this situation! 🙌 

I've got a bit of specific feedback and then some questions about the approach.

2022-05-24 21:39 UTC, juliasilge commented on R/misc.R
> +        ))
For consistence we use the [tidyverse style guide](https://style.tidyverse.org/documentation.html#r-code) which has no special font or anything for package names:

```suggestion
        glue::glue_collapse(c(
          "\nThis specification is available in the  ",
          cli::col_yellow(all$pkg[[1]]),
          " package. \n"
        ))
```

I'm a bit worried about the `\n` in this message and how that may interact with the rlang messages. Can we use the built-in bulleting, etc instead of hardcoding new lines into the message? 

Why is this `glue_collapse()` instead of just `glue()`. Because there can be more than one? Maybe we should use the pluralization from cli?

2022-05-24 21:39 UTC, juliasilge commented on R/bag_mars.R
> +  if (!is.null(x$method$fit$args) && has_loaded_implementation(class(x)[1], x$engine, x$mode)) {
How about a new little function `is_printable_spec(x)` (or something like that) to wrap this up? I worry about us having to make changes in so many places.

2022-05-24 21:39 UTC, juliasilge commented on R/misc.R
> +        ))
I think this function should return a named character vector, with no name for the first element, `i` for the others, etc, to be used as `message` in `rlang::inform()`.

2022-05-24 21:39 UTC, juliasilge commented on R/misc.R
> +      "specifications using the `{engine_}` engine."
```suggestion
      'parsnip could not locate an implementation for `{spec_}`, for {mode_} and the  `"{engine_}"` engine'
```

I like to write long `glue()` lines using `\\` rather than manually breaking with commas. One of the benefits of glue, I think!

2022-05-24 21:39 UTC, juliasilge commented on R/misc.R
> +    dplyr::filter(model == spec_, !!eng_cond, mode %in% mode_, is.na(pkg))
Is this an expensive check to do every time `new_model_spec()` is run (which is run a lot, I think)? The `env` is just there, but what about reading the file?

2022-05-25 15:17 UTC, simonpcouch commented on R/bag_mars.R
> +  if (!is.null(x$method$fit$args) && has_loaded_implementation(class(x)[1], x$engine, x$mode)) {
I agree that this conditional is a bit gnarly, especially given how many places it appears. Went ahead and implemented your change + I’m planning to follow up this PR with a refactor of print methods that should reduce this duplication quite a bit. :)

2022-05-25 15:19 UTC, simonpcouch commented on R/misc.R
> +        ))
Thank you for the nudges on making better use of glue and inform—learned a lot about those functions from your comments.

The message now reads:

``` r
library(parsnip)

C5_rules()
#> parsnip could not locate an implementation for `C5_rules` classification model specifications using the `C5.0` engine.
#> ℹ  The parsnip extension package rules implements support for this specification.
#> ℹ  Please install (if needed) and load to continue.
#> 
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0

C5_rules(engine = "C5.0") %>% translate()
#> parsnip could not locate an implementation for `C5_rules` classification model specifications using the `C5.0` engine.
#> ℹ  The parsnip extension package rules implements support for this specification.
#> ℹ  Please install (if needed) and load to continue.
#> 
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0
```

<sup>Created on 2022-05-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

and the code to get there is a good bit cleaner.

(Acknowledgement that I’m a serial violator of the no-special-package-name-formatting convention.🫠  Sorry.)

2022-05-25 15:25 UTC, simonpcouch commented on R/misc.R
> +    dplyr::filter(model == spec_, !!eng_cond, mode %in% mode_, is.na(pkg))
Certainly more expensive than our other checks. But—

* It’s only run on initiation of new model types (i.e. never at `set_engine`, `update`, etc)
* It’s possibly negligible compared to fit times:

``` r
library(parsnip)

# running the check
system.time(mod <- C5_rules())
#> parsnip could not locate an implementation for `C5_rules` classification model specifications using the `C5.0` engine.
#> ℹ The parsnip extension package rules implements support for this specification.
#> ℹ Please install (if needed) and load to continue.
#>    user  system elapsed 
#>   0.038   0.001   0.039

# doesn't run the check
system.time(mod <- mod %>% set_engine("C5.0"))
#>    user  system elapsed 
#>   0.008   0.000   0.009

# model fit to a lil fella
library(rules)

mtcars$cyl <- as.factor(mtcars$cyl)

system.time(mod %>% fit(cyl ~ ., mtcars))
#>    user  system elapsed 
#>   0.445   0.020   0.467
```

<sup>Created on 2022-05-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

2022-05-26 17:48 UTC, juliasilge requested changes

2022-05-26 17:48 UTC, juliasilge commented on R/misc.R
> +  if (nrow(avail) == 0 && nrow(all) > 0) {
Can we add a test that prints the first msg but not this bit?

2022-05-26 17:48 UTC, juliasilge commented on R/misc.R
> +prompt_missing_implementation <- function(spec_, engine_, mode_) {
```suggestion
inform_missing_implementation <- function(spec_, engine_, mode_) {
```
This will help for future reading, I think, to clarify what this is being used for

2022-05-26 17:48 UTC, juliasilge commented on R/misc.R
> +    dplyr::filter(model == spec_, !!eng_cond, mode %in% mode_, is.na(pkg))
The fact that it could be common to read this file multiple times seems like something to check and get other feedback on. We could read this file one time at `.onLoad` or something? Let's have one more person look at this part of the PR and see what they think.

2022-05-26 17:48 UTC, juliasilge commented on R/misc.R
> +new_model_spec <- function(cls, args, eng_args, mode, method, engine, new = TRUE) {
What do you think about `check_missing_spec = TRUE`? Since this argument is less about whether the spec is new or not and more about whether it will be checked?

2022-05-27 16:10 UTC, simonpcouch commented on R/misc.R
> +new_model_spec <- function(cls, args, eng_args, mode, method, engine, new = TRUE) {
That's definitely better—4dd0fb9.

2022-05-27 16:13 UTC, simonpcouch commented on R/misc.R
> +prompt_missing_implementation <- function(spec_, engine_, mode_) {
Sure thing—6c06315!

2022-05-27 16:22 UTC, simonpcouch commented on R/misc.R
> +    dplyr::filter(model == spec_, !!eng_cond, mode %in% mode_, is.na(pkg))
I think that's a good observation. After [9918043](https://github.com/tidymodels/parsnip/pull/732/commits/9918043a135e0782d40f3233335642f23666c53f), parsnip now assigns the `models.tsv` system file as `model_info_table` internally so we can skip that load step on checks:

``` r
library(parsnip)
  
# now just assigns models.tsv to internal object:
head(parsnip:::model_info_table)
#>      model                mode engine      pkg
#> 1 bag_mars      classification  earth baguette
#> 2 bag_mars          regression  earth baguette
#> 3 bag_tree censored regression  rpart censored
#> 4 bag_tree      classification   C5.0 baguette
#> 5 bag_tree      classification  rpart baguette
#> 6 bag_tree          regression  rpart baguette

# running the check. used to be:
#>    user  system elapsed 
#>   0.038   0.001   0.039
system.time(mod <- C5_rules())
#> parsnip could not locate an implementation for `C5_rules` classification model specifications using the `C5.0` engine.
#> ℹ The parsnip extension package rules implements support for this specification.
#> ℹ Please install (if needed) and load to continue.
#>    user  system elapsed 
#>   0.033   0.001   0.033


# doesn't run the check. used to be:
#>    user  system elapsed 
#>   0.008   0.000   0.009
system.time(mod <- mod %>% set_engine("C5.0"))
#>    user  system elapsed 
#>   0.007   0.000   0.007


# model fit to a lil fella, for comparison
library(rules)

mtcars$cyl <- as.factor(mtcars$cyl)

system.time(mod %>% fit(cyl ~ ., mtcars))
#>    user  system elapsed 
#>   0.440   0.025   0.464
```

<sup>Created on 2022-05-27 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

I opted not to ditch that `models.tsv` file entirely as it seems our machinery to keep it updated with the current docs system works well.

2022-05-27 16:23 UTC, simonpcouch commented
This should be ready for your review, @topepo! 

One unresolved discussion that we'd especially appreciate your eye on: https://github.com/tidymodels/parsnip/pull/732#discussion_r880971596

2022-05-27 17:35 UTC, juliasilge commented on R/misc.R
> +  if (nrow(avail) == 0 && nrow(all) > 0) {
Am I just missing seeing a test like this?

2022-05-27 18:03 UTC, simonpcouch commented on R/misc.R
> +  if (nrow(avail) == 0 && nrow(all) > 0) {
Oh, woops—somehow missed this. Added in [51ffc03](https://github.com/tidymodels/parsnip/pull/732/commits/51ffc0371f3f9d398a2a27733202b5131f4b7073). :)

2022-05-27 18:21 UTC, juliasilge approved these changes

2022-05-29 14:04 UTC, topepo commented on R/misc.R
> +  utils::read.delim(system.file("models.tsv", package = "parsnip"))
Can you do the same without using this file? The parsnip model env is the best representation of when packages are required for an engine.

2022-05-30 20:04 UTC, simonpcouch commented on R/misc.R
> +  utils::read.delim(system.file("models.tsv", package = "parsnip"))
@topepo I'm not sure we can.

Could you confirm that the needed extension package is not reflected in the model environment if that package is not loaded? e.g.

``` r
library(parsnip)
  
m_env <- parsnip::get_model_env()
m_env$C5_rules_pkgs
#> # A tibble: 0 × 3
#> # … with 3 variables: engine <chr>, pkg <list>, mode <chr>
m_env$C5_rules
#> # A tibble: 0 × 2
#> # … with 2 variables: engine <chr>, mode <chr>

C5_rules()
#> parsnip could not locate an implementation for `C5_rules` classification model specifications using the `C5.0` engine.
#> ℹ The parsnip extension package rules implements support for this specification.
#> ℹ Please install (if needed) and load to continue.
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0

library(rules)

m_env_ <- parsnip::get_model_env()
m_env_$C5_rules_pkgs
#> # A tibble: 1 × 3
#>   engine pkg       mode          
#>   <chr>  <list>    <chr>         
#> 1 C5.0   <chr [2]> classification

C5_rules()
#> C5.0 Model Specification (classification)
#> 
#> Computational engine: C5.0
```

<sup>Created on 2022-05-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Using the model environment instead wouldn't supply the information we need, I think—the purpose of this prompt is to nudge users to load a specific, needed extension package into their model environment if we can identify which one they need.

2022-05-31 15:33 UTC, simonpcouch commented on R/misc.R
> +  utils::read.delim(system.file("models.tsv", package = "parsnip"))
(Discussed in meeting—thumbs up from Max here.)

2022-05-31 16:20 UTC, simonpcouch commented
Note from meeting: thumbs up from Max to merge!

2022-05-31 16:21 UTC, merged