Engine docs for h2o
tidymodels/parsnip pull request #748
Opened 2022-06-06 18:00 UTC by qiushiyan

2022-06-06 19:30 UTC, simonpcouch commented
You may want to add "agua" to this vector:

https://github.com/tidymodels/parsnip/blob/78e8e16f822f74efaefef2b1d492c64f48979d09/R/engine_docs.R#L50-L53

 and re-document so that parsnip knows where the h2o support lives and can document it in `models.tsv`. :)

2022-06-06 21:29 UTC, qiushiyan commented
> 

Max already had it in https://github.com/tidymodels/parsnip/commit/1b3da0114a32608c768685cff161cfa1c9ae1f99. I have updated `inst/models.tsv` as well, thanks.

2022-06-07 17:24 UTC, simonpcouch commented on inst/models.tsv
> +"boost_tree"	"classification"	"h2o"	NA
Ah, I see. The `pkg` entry is NA for these because a duplicated `set_dependency` is needed in your model registration code in agua.

See [here](https://github.com/tidymodels/bonsai/blob/main/R/lightgbm_data.R#L16-L28) for an example—where you have `"h2o"` `"h2o"` in calls to `set_dependency` (like [here](https://github.com/tidymodels/agua/blob/main/R/model_engines.R#L102)), you also need an `"h2o"` `"agua"`.

Once that's situated, re-installing agua and then re-running `parsnip::update_model_info_file()` should update those missing values accordingly. :)

2022-06-07 17:35 UTC, qiushiyan commented on inst/models.tsv
> +"boost_tree"	"classification"	"h2o"	NA
Thanks! Fixed it in agua.

2022-06-07 17:37 UTC, simonpcouch commented on inst/models.tsv
> +"boost_tree"	"classification"	"h2o"	NA
Sweet, bravo!🌊

2022-06-09 11:40 UTC, topepo requested changes
Looks great. One suggestion below. 

In the aqua PR, I mentioned making an engine for `poisson_reg()` so make sure to add that file here too.

2022-06-09 11:40 UTC, topepo commented on man/rmd/boost_tree_h2o.Rmd
> +## Other details
You can make an Rmd template that that has something like

```
## Initializing h2o

To use h2o with tidymodels, please run `h2o::h2o.init()` (blah blah blah)

To stop using h2o, run `h2o::h2o.shutdown()`
```

and include the template in the h2o engine files. 

We might also mention there that you can do multiple threads (by default) in `h2o.init()` but the usually parallel processing with tidymodels also works and that it will decrease tuning time.

2022-06-09 11:40 UTC, topepo commented on man/rmd/mlp_h2o.Rmd
> +The naming of activation functions in [h2o::h2o.deeplearning()] differs from parsnip's conventions. Currently, only "relu" and "tanh" are supported and will be converted internally to "Rectifier" and
👍 on these parts

2022-06-09 11:40 UTC, topepo commented on man/rmd/mlp_h2o.Rmd
> +- h2o uses a 50% dropout ratio controlled by `dropout` for hidden layers by default. [h2o::h2o.deeplearning()] provides an engine argument `input_dropout_ratio` for dropout ratios in the input layer,
I did not know this. Good catch

2022-06-09 20:34 UTC, qiushiyan commented on man/rmd/boost_tree_h2o.Rmd
> +## Other details
template added [man/rmd/template-h2o-init.Rmd](https://github.com/tidymodels/parsnip/pull/748/files#diff-a383b8c5aa4b72f499c26045daeec384842cd337b923d6f08b1b19a42c4030ec)

2022-06-11 23:14 UTC, merged