improve prompting about missing implementations
tidymodels/parsnip pull request #793
Opened 2022-08-17 20:27 UTC by simonpcouch

Follows up on #732 and #778. The goal here is to tighten the logic for prompts about missing implementations. This PR eliminates false positives and makes sure we always suggest "registered" extension packages when they could be relevant.

To do so, we defer model specification checking for type / engine / mode combinations until we have some sort of clue that the user might be "done" specifying the model (If only we could `<-.model_spec`😭). This is at:

* `print`
* `fit`

...and functions that use either downstream. Some examples of how these prompts used to be raised:

``` r
library(parsnip)

# errors with a default engine, though doesn't call out baguette
bag_tree()
#> parsnip could not locate an implementation for `bag_tree` model specifications
#> using the `rpart` engine.
#> Bagged Decision Tree Model Specification (unknown)
#> 
#> Main Arguments:
#>   cost_complexity = 0
#>   min_n = 2
#> 
#> Computational engine: rpart

# bad: still includes default engine in error, bc triggered in bag_tree(),
# and still does not point to baguette
bag_tree() %>%
  set_engine("C5.0")
#> parsnip could not locate an implementation for `bag_tree` model specifications
#> using the `rpart` engine.
#> Bagged Decision Tree Model Specification (unknown)
#> 
#> Main Arguments:
#>   cost_complexity = 0
#>   min_n = 2
#> 
#> Computational engine: C5.0

# this should call out "censored regression" specifically, but does
# not because the error is triggered in bag_tree().
# also does not point to censored
bag_tree() %>%
  set_engine("rpart") %>%
  set_mode("censored regression")
#> parsnip could not locate an implementation for `bag_tree` model specifications
#> using the `rpart` engine.
#> Bagged Decision Tree Model Specification (censored regression)
#> 
#> Main Arguments:
#>   cost_complexity = 0
#>   min_n = 2
#> 
#> Computational engine: rpart

# this is well-defined:
library(censored)
#> Loading required package: survival

bag_tree() %>% 
  set_mode("censored regression") %>% 
  set_engine("rpart")
#> Bagged Decision Tree Model Specification (censored regression)
#> 
#> Main Arguments:
#>   cost_complexity = 0
#>   min_n = 2
#> 
#> Computational engine: rpart

# this errors differently when just censored is loaded
# ought to note that an implementation does live in baguette
bag_tree() %>%
  set_engine("C5.0")
#> Error in `check_spec_mode_engine_val()`:
#> ! Engine 'C5.0' is not supported for `bag_tree()`. See `show_engines('bag_tree')`.

# once baguette is loaded, this is well-defined:
library(baguette)

bag_tree() %>%
  set_engine("C5.0")
#> Bagged Decision Tree Model Specification (unknown)
#> 
#> Main Arguments:
#>   cost_complexity = 0
#>   min_n = 2
#> 
#> Computational engine: C5.0
```

<sup>Created on 2022-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Same code with the dev version:

``` r
library(parsnip)

# good: errors with a default engine
bag_tree()
#> ! parsnip could not locate an implementation for `bag_tree` model
#>   specifications using the `rpart` engine.
#> ℹ The parsnip extension packages censored and baguette implement
#>   support for this specification.
#> ℹ Please install (if needed) and load to continue.
#> 
#> Bagged Decision Tree Model Specification (unknown)
#> 
#> Main Arguments:
#>   cost_complexity = 0
#>   min_n = 2
#> 
#> Computational engine: rpart

# now includes correct engine in error
bag_tree() %>%
  set_engine("C5.0")
#> ! parsnip could not locate an implementation for `bag_tree` model
#>   specifications using the `C5.0` engine.
#> ℹ The parsnip extension package baguette implements support for this
#>   specification.
#> ℹ Please install (if needed) and load to continue.
#> 
#> Bagged Decision Tree Model Specification (unknown)
#> 
#> Main Arguments:
#>   cost_complexity = 0
#>   min_n = 2
#> 
#> Computational engine: C5.0

# calls out "censored regression" specifically
bag_tree() %>%
  set_engine("rpart") %>%
  set_mode("censored regression")
#> ! parsnip could not locate an implementation for `bag_tree` censored regression
#>   model specifications using the `rpart` engine.
#> ℹ The parsnip extension package censored implements support for this
#>   specification.
#> ℹ Please install (if needed) and load to continue.
#> 
#> Bagged Decision Tree Model Specification (censored regression)
#> 
#> Main Arguments:
#>   cost_complexity = 0
#>   min_n = 2
#> 
#> Computational engine: rpart

# this is well-defined:
library(censored)
#> Loading required package: survival

bag_tree() %>% 
  set_mode("censored regression") %>% 
  set_engine("rpart")
#> Bagged Decision Tree Model Specification (censored regression)
#> 
#> Main Arguments:
#>   cost_complexity = 0
#>   min_n = 2
#> 
#> Computational engine: rpart

# this now prompts informatively, as before censored was loaded
bag_tree() %>%
  set_engine("C5.0")
#> ! parsnip could not locate an implementation for `bag_tree` model
#>   specifications using the `C5.0` engine.
#> ℹ The parsnip extension package baguette implements support for this
#>   specification.
#> ℹ Please install (if needed) and load to continue.
#> 
#> Bagged Decision Tree Model Specification (unknown)
#> 
#> Main Arguments:
#>   cost_complexity = 0
#>   min_n = 2
#> 
#> Computational engine: C5.0

library(baguette)

# prompt goes away once baguette is loaded
bag_tree() %>%
  set_engine("C5.0")
#> Bagged Decision Tree Model Specification (unknown)
#> 
#> Main Arguments:
#>   cost_complexity = 0
#>   min_n = 2
#> 
#> Computational engine: C5.0
```

<sup>Created on 2022-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

When passed to `fit` rather than `print`, the prompt is an error rather than a message:

``` r
library(parsnip)

bag_tree() %>%
  set_engine("rpart") %>%
  set_mode("censored regression") %>%
  fit(mpg ~ ., mtcars)
#> Error in `prompt_missing_implementation()`:
#> ! parsnip could not locate an implementation for `bag_tree` censored
#>   regression model specifications using the `rpart` engine.
#> ℹ The parsnip extension package censored implements support for this
#>   specification.
#> ℹ Please install (if needed) and load to continue.
```

<sup>Created on 2022-08-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This also catches bugs related to how loading one unrelated extension would affect the prompts related to another. PR on its way to extratests to make sure we test this as well!

Open to ideas if we have any other cues that a user may be "done" putting together a model spec—adding to a workflow is another instance, though we'll get "automatic" workflow support otherwise in that it wraps parsnip's print and fit methods.

2022-08-29 12:28 UTC, simonpcouch commented
Note: [this community post](https://community.rstudio.com/t/rule-fit-using-tidy-models-error/145913) points out additional locations where we might want to drop these checks, none of which live in parsnip—`workflows::add_model` and `workflows::extract_parameter_set_dials.workflow`.  May be worth exporting helpers.

2022-08-31 15:27 UTC, topepo requested changes
I'll run this with TMwR and our workshop notes to test more. 

Can you run revdeps?

2022-08-31 15:27 UTC, topepo commented on R/aaa_models.R
> +model_info_table <-
This should probably be an internal function and not in open code. We only use it once (inside `check_spec_mode_engine_val()`) and the function should be invoked there.

2022-08-31 15:27 UTC, topepo commented on R/misc.R
> +implementation_exists_somewhere <- function(cls,
Informative name but excessive length. Can you rename?

2022-08-31 15:27 UTC, topepo commented on R/misc.R
> +implementation_exists_somewhere <- function(cls,
Also, `cls` can be derived from `object` so maybe just have `object` and `user_specified_engine` as arguments?

2022-08-31 15:27 UTC, topepo commented on R/bag_mars.R
> +      user_specified_mode = !missing(mode),
These changes will have to propagate to the external extension packages too (e.g. model time)?

We'll also need to update the docs on tidymodels.org too (I believe).

2022-08-31 15:27 UTC, topepo commented on R/engines.R
> +  if (!implementation_exists_somewhere(mod_type,
Can you add some comments (here?) about the strategy we are using to check the mode?

2022-08-31 15:27 UTC, topepo commented on R/fit.R
> +      prompt_missing_implementation(
Named arguments please.

2022-08-31 15:27 UTC, topepo commented on R/misc.R
> +engine_filter_condition <- function(engine, user_specified_engine) {
It's hard to read this and know what it does. It is returning an expression (or `TRUE`) that is used in `filter()`?

2022-08-31 15:27 UTC, topepo commented on R/misc.R
> +    "!" = glue::glue(
Can we put the package name in single quotes (or something else)? Due to the weird way I name packages, this can look like a typo or something.

2022-08-31 15:45 UTC, simonpcouch commented
Thanks for the review! Running revdeps and addressing comments ATM.

2022-08-31 15:54 UTC, simonpcouch commented on R/bag_mars.R
> +      user_specified_mode = !missing(mode),
`engine_filter_condition` and `mode_filter_condition` (to be renamed re: comment), where these slots are processed, anticipate model objects from external extension packages not having this slot—in those cases, we bypass the additional prompts so that those external extensions fall back to the same errors as before. Those extensions can add the slot and get the prompting introduced in this PR "for free," since these prompts look to a full join of the model environment and `model_info_table`.

Good thought on the tidymodels.org docs. Will follow-up with a PR there.

2022-08-31 16:13 UTC, simonpcouch commented
No new problems in revdeps, though I found a backward-compatibility issue that wasn't caught.

2022-08-31 16:46 UTC, simonpcouch commented on R/misc.R
> +implementation_exists_somewhere <- function(cls,
Renamed to `spec_is_possible`! Correct that the arguments could be derived from a complete model object, but we use this to test a new "proposed" object in `set_mode` and `set_engine`. e.g. in `set_mode.model_spec`:

```
  if (!spec_is_possible(cls,
                        object$engine, object$user_specified_engine,
                        mode, user_specified_mode = TRUE))
```

where `mode` was supplied to `set_mode`.

Maybe we can set defaults based on `object` slots and then override them where needed?

2022-08-31 16:47 UTC, simonpcouch commented on R/aaa_models.R
> +model_info_table <-
Implemented in [e99dfd5](https://github.com/tidymodels/parsnip/pull/793/commits/e99dfd55115ca4dc36098527faea2da1dd2a710f)!

2022-08-31 16:48 UTC, simonpcouch commented on R/misc.R
> +engine_filter_condition <- function(engine, user_specified_engine) {
Added comments in [e99dfd5](https://github.com/tidymodels/parsnip/pull/793/commits/e99dfd55115ca4dc36098527faea2da1dd2a710f):

```
# return a condition for use in `dplyr::filter()` on model info.
# if the user specified an engine and the model object reflects that in
# the `user_specified_engine` slot, filter the model info down to
# those that the user specified. if not, don't filter the model info at all.
```

2022-08-31 17:22 UTC, simonpcouch commented on R/misc.R
> +    "!" = glue::glue(
I wrapped parsnip with the same cli `.pkg` tag as the recommended packages. Does that address this, or were you referring to the recommended packages as well?

2022-08-31 17:23 UTC, simonpcouch commented on R/fit.R
> +      prompt_missing_implementation(
Addressed in [8145467](https://github.com/tidymodels/parsnip/pull/793/commits/8145467e3eee9aa498009509f0a2791653ebf2e7)!

2022-08-31 17:23 UTC, simonpcouch commented on R/engines.R
> +  if (!implementation_exists_somewhere(mod_type,
Addressed in [8145467](https://github.com/tidymodels/parsnip/pull/793/commits/8145467e3eee9aa498009509f0a2791653ebf2e7)! Commented in `set_mode`, `set_engine`, and `new_model_spec`.

2022-08-31 18:04 UTC, simonpcouch commented
The most recent commit exports and documents the relationship between the different checking functions more thoroughly:


> The helpers `spec_is_possible()`, `spec_is_loaded()`, and
> `prompt_missing_implementation()` provide tooling for checking
> model specifications. In addition to the `cls`, `engine`, and `mode`
> arguments, the functions take arguments `user_specified_engine` and
> `user_specified_mode`, denoting whether the user themselves has
> specified the engine or mode, respectively.
> 
> `spec_is_possible()` checks against the union of
> 
> * the current parsnip model environment and
> * the `model_info_table` of "pre-registered" model specifications
> 
> to determine whether a model is well-specified. See
> `parsnip:::read_model_info_table()` for this table.
> 
> `spec_is_loaded()` checks only against the current parsnip model environment.
> 
> `spec_is_possible()` is executed automatically on `new_model_spec()`,
> `set_mode()`, and `set_engine()`, and `spec_is_loaded()` is executed
> automatically in `print.model_spec()`, among other places. `spec_is_possible()`
> should be used when a model specification is still "in progress" of being
> specified, while `spec_is_loaded` should only be called when parsnip or an
> extension receives some indication that the user is "done" specifying a model
> specification: at print, fit, addition to a workflow, or `extract_*()`, for
> example.
> 
> When `spec_is_loaded()` is `FALSE`, the `prompt_missing_implementation()`
> helper will construct an informative message to prompt users to load or
> install needed packages. It's `prompt` argument refers to the prompting
> function to use, usually `cli::cli_inform` or `cli::cli_abort`, and the
> ellipses are passed to that function.

2022-09-06 21:24 UTC, topepo commented on R/misc.R
> +    "!" = glue::glue(
Nope, your changes are perfect

2022-09-06 21:24 UTC, merged